//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PShop.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public Nullable<int> Id_Pen { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> SumOrder { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pen Pen { get; set; }
    }
}
